name: update_lists

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run searchfilter.sh
        run: sh ./searchfilter.sh
      - name: update respository content
        run: |
          git status
          git config --global user.email "randomtest@git.com"
          git config --global user.name "Experimenter99"
          git add .
          git commit -m "Auto update output filter lists"
          git push 
